version: "3"

services:
  database:
    image: "bitnami/postgresql"
    ports:
      - "5433:5432" # Porta alterada para evitar conflito
    env_file:
      - ./.env
    volumes:
      - "postgresql_data:/bitnami/postgresql"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182 # Porta alterada para evitar conflito
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22182:2182 # Porta alterada para evitar conflito

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29093:29092 # Porta alterada para evitar conflito
    environment:
      KAFKA_BROKER_ID: 2 # Broker ID alterado para evitar conflito
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182 # Conectando à nova porta do Zookeeper
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:29093 # Porta alterada
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8081:8080 # Porta alterada para evitar conflito
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2182 # Conectando à nova porta do Zookeeper
      KAFKA_CLUSTERS_0_NAME: classroom
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093 # Porta alterada

volumes:
  postgresql_data:
    driver: local
